# 5 更多的 Tensor 操作

## 1 Tensor 的拼接

在 PyTorch 中，我们可以根据不同的需求选择 `torch.cat()`、`torch.stack()`、`torch.hstack()` 或 `torch.vstack()` 方法进行 Tensor 拼接。在使用这些方法时，需要确保参与拼接的 Tensor 具有相同的形状（除拼接维度外）并且数据类型相同。

### 1.1 torch.cat(): 沿着已存在的维度进行拼接

当需要将多个具有相同形状的 Tensor 沿着某个维度拼接时，可以使用 `torch.cat()`。参与拼接的 Tensor 必须具有相同的形状（除拼接维度外），并且数据类型相同。

```python
torch.cat(tensors, dim=0, out=None)
```

In [4]:
import torch

tensor1 = torch.ones(3, 3)
tensor2 = 2*torch.ones(3, 3)

# 竖向 0轴 上的拼接
result0 = torch.cat((tensor1, tensor2), dim=0)
print(result0)

# 竖向 1轴 上的拼接
result1 = torch.cat((tensor1, tensor2), dim=1)
print(result1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.],
        [1., 1., 1., 2., 2., 2.]])


### 1.2 torch.stack(): 在新的维度上进行拼接

当需要将多个具有**相同形状**的 Tensor 在新的维度上拼接时，可以使用 `torch.stack()`。参与拼接的 Tensor 必须具有相同的形状，并且数据类型相同。stack() 拼接会增加维度

```python
torch.stack(tensors, dim=0, out=None)
```

In [7]:
tensor1 = torch.arange(0,4)
tensor2 = torch.arange(5,9)

result0 = torch.stack((tensor1, tensor2), dim=0)
print(result0)

result1 = torch.stack((tensor1,tensor2), dim=1)
print(result1)

tensor([[0, 1, 2, 3],
        [5, 6, 7, 8]])
tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]])


### 1.3 torch.hstack() 和 torch.vstack(): 水平方向和垂直方向的拼接

当需要在水平方向或垂直方向拼接多个具有相同形状的 Tensor 时，可以使用 `torch.hstack()` 或 `torch.vstack()`。这两种拼接不会增加张量的维度。

```python
torch.hstack(tensors, *, out=None)
torch.vstack(tensors, *, out=None)
```

In [12]:
tensor1 = torch.ones(2, 2)
tensor2 = 2*torch.ones(2, 2)

result_h = torch.hstack((tensor1, tensor2))
print(result_h)

result_v = torch.vstack((tensor1, tensor2))
print(result_v)

torch.Size([2, 2])
tensor([[1., 1., 2., 2.],
        [1., 1., 2., 2.]])
torch.Size([2, 4])
tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])


## 2 Tensor 的切分

在深度学习的场景中，为了达到提高计算和空间效率，实现分布式计算等目的，需要将 Tensor 进行切分。切分后的小Tensor更容易计算和处理,并且具有更高的灵活性。

### 2.1 torch.chunk() 

将一个 Tensor 沿着指定维度（轴）切分成**多个相同大小**的子 Tensor

```python
torch.chunk(input, chunks, dim=0)
```

chunks 参数表示希望得到的子 Tensor 数量。请确保输入 Tensor 可以平均切分。否则，最后一个子 Tensor 的大小可能小于其他子 Tensor。子 Tensor的大小是 input 除以 chunks 的结果向上取整


In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

chunks0 = torch.chunk(x, 2, 0)
for chunk in chunks0:
    print(chunk)

chunks1 = torch.chunk(x, 2, 1)
for chunk in chunks1:
    print(chunk)



tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]])


### 2.2 torch.split()

将一个 Tensor 沿着指定维度（轴）切分成**多个指定大小**的子 Tensor

```python
torch.split(input, split_size_or_sections, dim=0)
```

split_size_or_sections 参数可以是一个整数，表示每个子 Tensor 的大小，或者一个列表，表示每个子 Tensor 的大小不同。保输入 Tensor 可以根据所需的大小进行切分, 否则将引发错误。


In [24]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
split_sizes = torch.split(x, 2, 0)
for split in split_sizes:
    print(split)

print("="*25)
split_sizes = torch.split(x, [1,2,1], 0)
for split in split_sizes:
    print(split)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[1, 2, 3]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[10, 11, 12]])


### 2.3 torch.unbind() 

将输入 Tensor 沿指定维度（轴）拆分为元组，元组中每个元素是一个子 Tensor

```python
torch.unbind(input, dim=0)
```

dim 参数表示希望沿哪个维度（轴）拆分 Tensor。请确保输入 Tensor 的该维度大小大于 0。


In [27]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
unbound_tensors = torch.unbind(x, 0)

for tensor in unbound_tensors:
    print(tensor)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([7, 8, 9])
tensor([10, 11, 12])


### 2.4 torch.narrow() 

从一个 Tensor 沿着指定维度（轴）截取一部分

```python
torch.narrow(input, dim, start, length)
```
start 参数表示截取的起始位置，length 参数表示截取的长度。需确保起始位置和长度在输入 Tensor 的范围内。

In [29]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# 沿x的0轴，将，从第1个元素截取长度为2的 Tensor
narrowed = torch.narrow(x, 0, 1, 2)

print(narrowed)

tensor([[4, 5, 6],
        [7, 8, 9]])




## 3 Tensor 的索引

### 3.1 基本索引

当需要访问或修改 Tensor 中的特定元素时，可以使用基本索引。需确保索引在输入 Tensor 的范围内。


In [30]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = x[1, 2]  # 访问第 1 行，第 2 列的元素
print(element)

x[0, 1] = 42  # 修改第 0 行，第 1 列的元素
print(x)

tensor(6)
tensor([[ 1, 42,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])


### 3.2 切片索引

当需要访问或修改 Tensor 中的一部分元素时，可以使用切片索引。


In [31]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_x = x[:, 1:]  # 访问所有行，第 1 列及以后的元素
print(sub_x)

x[2, 1:] = torch.tensor([42, 43])  # 修改第 2 行，第 1 列及以后的元素
print(x)

tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, 42, 43]])


### 3.3 index_select

当你需要沿指定维度（轴）从 Tensor 中选择多个子 Tensor 时，可以使用 torch.index_select() 函数。

```python
torch.index_select(input, dim, index)
```

- input：输入 Tensor。
- dim：指定维度（轴），沿此维度选择子 Tensor。
- index：一个一维张量，包含要选择的索引。


In [33]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
selected_rows = torch.index_select(x, 0, torch.tensor([0, 2]))  # 选择第 0 行和第 2 行
print(selected_rows)

selected_cols = torch.index_select(x, 1, torch.tensor([0, 2]))  # 选择第 0 行和第 2 列
print(selected_cols)


tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[1, 3],
        [4, 6],
        [7, 9]])


### 3.4 masked_select

当需要根据一个布尔掩码 Tensor 从输入 Tensor 中选择元素时，可以使用 torch.masked_select

```python
torch.masked_select(input, mask)
```

- input：输入 Tensor
- mask：与输入 Tensor 形状相同的布尔掩码 Tensor, 必须与输入 Tensor 的形状相同

In [35]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = x > 5  # 创建一个布尔掩码 Tensor
print(mask)
selected_elements = torch.masked_select(x, mask)  # 选择大于 5 的元素
print(selected_elements)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([6, 7, 8, 9])
